{"name": "test_login_failure[standard_user-wrong_password-Username and password do not match]", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидалась ошибка: Username and password do not match\nassert 'Username and password do not match' in ''", "trace": "driver = <undetected_chromedriver.Chrome (session=\"274865d212882aa3e13d5dd83e6b4f47\")>, username = 'standard_user', password = 'wrong_password', expected_error_message = 'Username and password do not match'\n\n    @allure.story(\"Негативные тесты\")\n    @allure.story(\"Негативные тесты авторизации\")\n    @pytest.mark.parametrize(\n        \"username, password, expected_error_message\",\n        [\n            (\"standard_user\", \"wrong_password\", \"Username and password do not match\"),\n            (\"wrong_user\", \"secret_sauce\", \"Username and password do not match\"),\n            (\"\", \"\", \"Username is required\"),\n        ]\n    )\n    def test_login_failure(driver, username, password, expected_error_message):\n        with allure.step(\"Открываем страницу авторизации\"):\n            login_page = LogPage(driver)\n            login_page.open(URL)\n    \n        with allure.step(f\"Выполняем вход с параметрами: username={username}, password{password}\"):\n            login_page.enter_username(username)\n            login_page.enter_password(password)\n    \n        with allure.step(\"Проверяем сообщение об ошибке\"):\n            error_message = login_page.get_error_message()\n>           assert expected_error_message in error_message, f\"Ожидалась ошибка: {expected_error_message}\"\nE           AssertionError: Ожидалась ошибка: Username and password do not match\nE           assert 'Username and password do not match' in ''\n\ntests/test_login_page.py:49: AssertionError"}, "steps": [{"name": "Открываем страницу авторизации", "status": "passed", "start": 1733925196228, "stop": 1733925196532}, {"name": "Выполняем вход с параметрами: username=standard_user, passwordwrong_password", "status": "passed", "start": 1733925196533, "stop": 1733925196958}, {"name": "Проверяем сообщение об ошибке", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидалась ошибка: Username and password do not match\nassert 'Username and password do not match' in ''\n", "trace": "  File \"/media/grifftih/Linux/TestCases/SwagLabs/tests/test_login_page.py\", line 49, in test_login_failure\n    assert expected_error_message in error_message, f\"Ожидалась ошибка: {expected_error_message}\"\n"}, "start": 1733925196958, "stop": 1733925197063}], "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}, {"name": "expected_error_message", "value": "'Username and password do not match'"}], "start": 1733925196228, "stop": 1733925197080, "uuid": "ef6deef3-42de-4f82-bed8-8e79492297df", "historyId": "ae01116781b049999bef1c7a8c31a2db", "testCaseId": "75bc51d029e4608920585d699e2de0b6", "fullName": "tests.test_login_page#test_login_failure", "labels": [{"name": "story", "value": "Негативные тесты авторизации"}, {"name": "story", "value": "Негативные тесты"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "griffith"}, {"name": "thread", "value": "5151-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_page"}]}